export const regionOptions = [
  "Africa",
  "America",
  "Asia",
  "Central America",
  "Europe",
  "Latam",
  "Middle East",
  "NAFTA",
  "Other",
  "Southwest Pacific"
] as const;

export type Region = (typeof regionOptions)[number];

export const countryOptionsByRegion: Record<Region, readonly string[]> = {
  Africa: [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe"
  ],
  America: [
    "Antigua and Barbuda",
    "Argentina",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bolivia",
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Grenada",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Suriname",
    "Trinidad and Tobago",
    "United States",
    "Uruguay",
    "Venezuela"
  ],
  Asia: [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "Georgia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Kyrgyzstan",
    "Laos",
    "Macau",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "North Korea",
    "Pakistan",
    "Philippines",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "Timor-Leste",
    "Turkmenistan",
    "Uzbekistan",
    "Vietnam"
  ],
  "Central America": ["Belize", "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua", "Panama"],
  Europe: [
    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "United Kingdom",
    "Vatican City"
  ],
  Latam: [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela"
  ],
  "Middle East": [
    "Bahrain",
    "Egypt",
    "Iran",
    "Iraq",
    "Israel",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Oman",
    "Palestine",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "Turkey",
    "United Arab Emirates",
    "Yemen"
  ],
  NAFTA: ["Canada", "Mexico", "United States"],
  Other: ["Other"],
  "Southwest Pacific": [
    "Australia",
    "Fiji",
    "Kiribati",
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "New Zealand",
    "Palau",
    "Papua New Guinea",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu"
  ]
};

export function getCountryOptions(region: Region) {
  return countryOptionsByRegion[region];
}

export const expenseTypeOptions = [
  "Business Meals",
  "Entertainment and Gifts",
  "Flight Travel Approval",
  "Meals",
  "Other Expenses",
  "Stay",
  "Transport",
  "Travel Approval"
] as const;

export type ExpenseType = (typeof expenseTypeOptions)[number];

export const businessMealsSubExpenseOptions = ["Business Meals", "Dinner", "Lunch"] as const;
export const mealsSubExpenseOptions = ["Breakfast", "Brunch", "Dinner", "Drinks", "Lunch", "Snacks"] as const;
export const otherExpensesSubExpenseOptions = [
  "Any other expenses",
  "Bank Charges",
  "Donation/Gift",
  "Fitness/Gym fees",
  "Health Insurance",
  "Medical Fees",
  "Meeting Room",
  "Membership",
  "Office",
  "Office Rent",
  "Office Supplies",
  "Outing/Sports Ticket",
  "Passports & Visa",
  "Promotional Items",
  "Registration Fees",
  "Tips",
  "Training Fees"
] as const;
export const staySubExpenseOptions = [
  "Bar/Mini Bar",
  "Hotel",
  "Laundry",
  "Other Lodging Expenses",
  "Rent Housing",
  "Room Service",
  "Telephone Bill"
] as const;
export const transportSubExpenseOptions = [
  "Air",
  "Auto/Bus/Metro",
  "Car Rental",
  "Fuel",
  "Mileage (Personal Car)",
  "Other Transportation",
  "Parking",
  "Rail",
  "Taxi",
  "Toll"
] as const;

const subExpenseTypeOptionsByExpenseType: Record<ExpenseType, readonly string[]> = {
  "Business Meals": businessMealsSubExpenseOptions,
  "Entertainment and Gifts": ["Entertainment and Gifts"],
  "Flight Travel Approval": ["Flight Travel Approval"],
  Meals: mealsSubExpenseOptions,
  "Other Expenses": otherExpensesSubExpenseOptions,
  Stay: staySubExpenseOptions,
  Transport: transportSubExpenseOptions,
  "Travel Approval": ["Travel Approval"]
};

export const mealExpenseTypes = ["Business Meals", "Meals"] as const satisfies readonly ExpenseType[];

export function getSubExpenseTypeOptions(expenseType: ExpenseType) {
  return subExpenseTypeOptionsByExpenseType[expenseType] ?? [];
}

export function getDefaultSubExpenseType(expenseType: ExpenseType) {
  return getSubExpenseTypeOptions(expenseType)[0] ?? "General";
}

export function isMealExpenseType(expenseType: ExpenseType) {
  return (mealExpenseTypes as readonly ExpenseType[]).includes(expenseType);
}
