import type { CloudflareEnv } from "./types";

interface ExportPackageEmailContentInput {
  folderName: string;
  expenseCount?: number;
  generatedAt?: string;
}

export interface ExportPackageEmailInput extends ExportPackageEmailContentInput {
  recipient?: string;
  filename: string;
  zipBytes: Uint8Array;
}

export interface ExportPackageEmailResult {
  messageId: string;
  threadId: string;
  recipient: string;
  subject: string;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatGeneratedDate(value?: string) {
  if (!value) return undefined;

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return undefined;

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric"
  }).format(date);
}

function expenseCountLabel(expenseCount?: number) {
  if (typeof expenseCount !== "number") return "the expenses";
  return `${expenseCount} ${expenseCount === 1 ? "expense" : "expenses"}`;
}

function bytesToBase64(bytes: Uint8Array) {
  let binary = "";
  const chunkSize = 0x8000;

  for (let index = 0; index < bytes.length; index += chunkSize) {
    const chunk = bytes.subarray(index, index + chunkSize);
    for (const byte of chunk) {
      binary += String.fromCharCode(byte);
    }
  }

  return btoa(binary);
}

function requireAgentMailConfig(env: CloudflareEnv) {
  if (!env.AGENTMAIL_API_KEY) {
    throw new Error("AgentMail is not configured.");
  }

  return {
    apiKey: env.AGENTMAIL_API_KEY,
    inboxId: env.AGENTMAIL_INBOX_ID || "expense-me@agentmail.to",
    baseUrl: (env.AGENTMAIL_BASE_URL || "https://api.agentmail.to").replace(/\/+$/, "")
  };
}

function requireRecipient(inputRecipient: string | undefined, env: CloudflareEnv) {
  const recipient = (inputRecipient || env.EXPORT_PACKAGE_EMAIL_TO || "").trim();
  if (!recipient) {
    throw new Error("Export Package email recipient is not configured.");
  }

  return recipient;
}

export function buildExportPackageEmailContent(input: ExportPackageEmailContentInput) {
  const generatedDate = formatGeneratedDate(input.generatedAt);
  const countLabel = expenseCountLabel(input.expenseCount);
  const subject = `Expense Me Export Package - ${input.folderName}`;
  const textLines = [
    `Attached is the Expense Me Export Package for "${input.folderName}".`,
    `It includes ${countLabel}, the entry spreadsheet, receipt PDFs, declarations, reconciliation notes, and the PDF expense index for this Expense Folder.`,
    generatedDate ? `Generated on ${generatedDate}.` : undefined,
    "",
    "Generated by Expense Me."
  ].filter((line): line is string => line !== undefined);
  const safeFolderName = escapeHtml(input.folderName);
  const safeCountLabel = escapeHtml(countLabel);
  const generatedHtml = generatedDate ? `<p>Generated on ${escapeHtml(generatedDate)}.</p>` : "";

  return {
    subject,
    text: textLines.join("\n"),
    html: [
      "<!doctype html>",
      '<html><head><meta charset="utf-8"></head>',
      '<body style="font-family:Arial,sans-serif;line-height:1.5;color:#1b1430;">',
      `<p>Attached is the Expense Me Export Package for <strong>${safeFolderName}</strong>.</p>`,
      `<p>It includes ${safeCountLabel}, the entry spreadsheet, receipt PDFs, declarations, reconciliation notes, and the PDF expense index for this Expense Folder.</p>`,
      generatedHtml,
      "<p>Generated by Expense Me.</p>",
      "</body></html>"
    ].join("")
  };
}

export async function sendExportPackageEmail(
  env: CloudflareEnv,
  input: ExportPackageEmailInput,
  fetcher: typeof fetch = fetch
): Promise<ExportPackageEmailResult> {
  const config = requireAgentMailConfig(env);
  const recipient = requireRecipient(input.recipient, env);
  const content = buildExportPackageEmailContent(input);
  const response = await fetcher(
    `${config.baseUrl}/v0/inboxes/${encodeURIComponent(config.inboxId)}/messages/send`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        to: recipient,
        subject: content.subject,
        text: content.text,
        html: content.html,
        attachments: [{
          content: bytesToBase64(input.zipBytes),
          filename: input.filename,
          content_type: "application/zip"
        }]
      })
    }
  );

  if (!response.ok) {
    throw new Error(`AgentMail send failed: ${response.status}`);
  }

  const body = await response.json().catch(() => ({})) as {
    message_id?: string;
    messageId?: string;
    thread_id?: string;
    threadId?: string;
  };

  return {
    messageId: body.message_id ?? body.messageId ?? "",
    threadId: body.thread_id ?? body.threadId ?? "",
    recipient,
    subject: content.subject
  };
}
